LineLength:
  Enabled: no
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
MethodLength:
  Enabled: no
Metrics/AbcSize:
  Enabled: no
Metrics/BlockLength:
  Max: 90
Metrics/ClassLength:
  Enabled: no
Metrics/CyclomaticComplexity:
  Enabled: no
Metrics/LineLength:
  Enabled: no
Metrics/PerceivedComplexity:
  Enabled: no
Style/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: yes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/EndOfLine:
  Enabled: no