source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef',       '>= 12.5'
gem 'chefspec',   '>= 4.2'
gem 'fauxhai',    '>= 2.2'
gem 'foodcritic', '>= 4.0'
gem 'rake', '~> 10.1'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 0.37'
