name              'ms_dotnet45'
maintainer        'Tim Smith'
maintainer_email  'tsmith84@gmail.com'
license           'Apache 2.0'
license           'All rights reserved'
description       'Installs Microsoft .NET 4.5'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '2.0.0'
supports          'windows'
depends           'windows'
