name             'ms_dotnet-test'
maintainer       'Criteo'
maintainer_email 'b.courtois@criteo.com'
license          'Apache 2.0'
description      'Test cookbook for ms_dotnet'
long_description 'Test cookbook for ms_dotnet'
version          '0.0.0'
supports         'windows'
depends          'ms_dotnet'
